#!/usr/bin/env python3
"""Stamp a provenance footer onto a generated report.

Shared across jet52 projects: jetmemo, jetredline, jetbriefcheck, jetrehearing.

The footer records, for later validation and comparison as the tools and the
Claude models change:
    Report generated by <model> using <skill> v<version> on <YYYY-MM-DD>.

Design: the parts that can be sourced deterministically *are* — the skill
version (from SKILL.md frontmatter `version:`, then a VERSION file) and the
date (the system clock). The model identifier is supplied by the caller (the
orchestrator, which alone knows the runtime model); this script never guesses
the model, because a model naming its own release is exactly the unreliable
self-report a validation record must not depend on.

Idempotent: re-running replaces an existing footer rather than appending a
duplicate, so it is safe to call on every regeneration.

Usage:
    python3 provenance.py --file REPORT.md --model "Claude Opus 4.8 (claude-opus-4-8)"
    # optional: --date YYYY-MM-DD (defaults to today), --skill NAME, --skill-dir DIR

The skill name and version are derived from this script's own location
(<skill>/scripts/provenance.py), matching check_update.py, so the orchestrator
normally needs to pass only --file and --model.
"""

import argparse
import re
import sys
from datetime import date
from pathlib import Path

# Per-skill constant (like check_update.py). The skill directory may be a
# symlink to a dev checkout whose folder is not named after the skill, so the
# name is hardcoded rather than derived from the path.
SKILL_NAME = "jetrehearing"

# Matches a previously stamped footer (with or without the leading rule) at end
# of file, so re-stamping replaces rather than duplicates it.
_FOOTER_RE = re.compile(
    r"\n*(?:---\s*\n+)?\*Report generated by .+? using .+? on .+?\*\s*$",
    re.S,
)


def find_skill_dir(script_path: Path) -> Path:
    """Locate the skill root (holding SKILL.md / VERSION) from this script's path.

    Works whether the script lives in <skill>/scripts/ (jetmemo, jetrehearing)
    or directly in <skill>/ (jetredline). Resolves symlinks first, so a skill
    mounted as a symlink to a dev checkout still resolves correctly.
    """
    here = script_path.resolve()
    for d in (here.parent, here.parent.parent, here.parent.parent.parent):
        if (d / "SKILL.md").exists() or (d / "VERSION").exists():
            return d
    return here.parent.parent


def read_version(skill_dir: Path) -> str:
    """Authoritative version: SKILL.md frontmatter `version:`, then VERSION file."""
    skill_md = skill_dir / "SKILL.md"
    if skill_md.exists():
        m = re.search(r"^version:\s*(.+?)\s*$", skill_md.read_text(), re.M)
        if m:
            return m.group(1).strip().strip("'\"")
    version_file = skill_dir / "VERSION"
    if version_file.exists():
        return version_file.read_text().strip()
    return "unknown"


def footer_line(model: str, skill: str, version: str, on_date: str) -> str:
    ver = f"v{version}" if version != "unknown" else "version unknown"
    return (
        f"*Report generated by {model} using {skill} {ver} on {on_date}. "
        f"AI-generated first draft for internal use; verify all citations and "
        f"findings before relying.*"
    )


def stamp(path: Path, model: str, skill: str, version: str, on_date: str) -> None:
    text = path.read_text().rstrip()
    text = _FOOTER_RE.sub("", text).rstrip()
    path.write_text(text + "\n\n---\n\n" + footer_line(model, skill, version, on_date) + "\n")


def main() -> int:
    default_skill_dir = find_skill_dir(Path(__file__))

    ap = argparse.ArgumentParser(description="Stamp a provenance footer onto a report.")
    ap.add_argument("--file", required=True, help="Report file to stamp (markdown).")
    ap.add_argument("--model", required=True,
                    help='Runtime model identifier, e.g. "Claude Opus 4.8 (claude-opus-4-8)".')
    ap.add_argument("--skill", default=SKILL_NAME,
                    help="Skill name (defaults to this skill's SKILL_NAME constant).")
    ap.add_argument("--skill-dir", default=str(default_skill_dir),
                    help="Skill root holding SKILL.md / VERSION (defaults to this script's skill).")
    ap.add_argument("--date", default=date.today().isoformat(),
                    help="Generation date YYYY-MM-DD (defaults to today).")
    args = ap.parse_args()

    path = Path(args.file)
    if not path.exists():
        print(f"provenance: file not found: {path}", file=sys.stderr)
        return 1

    version = read_version(Path(args.skill_dir))
    stamp(path, args.model, args.skill, version, args.date)
    print(f"Stamped provenance: {args.skill} v{version} | {args.model} | {args.date}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
